apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: study-smart
type: Opaque
stringData:
  DB_USER: studysmart
  DB_PASSWORD: changeme
  DB_NAME: studysmart
  JWT_SECRET: 9d290da62ba21c180e0a8d70658a2b6ba3082968048d87b2e904051a22226ccc
  STRIPE_SECRET_KEY: sk_test_xxx