apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
  namespace: study-smart
type: Opaque
stringData:
  POSTGRES_USER: sonar
  POSTGRES_PASSWORD: sonar_password_2024
  SONAR_JDBC_USERNAME: sonar
  SONAR_JDBC_PASSWORD: sonar_password_2024

---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-admin-secret
  namespace: study-smart
type: Opaque
stringData:
  SONARQUBE_ADMIN_USER: admin
  SONARQUBE_ADMIN_PASSWORD: admin_password_2024
