sonar.projectKey=payment-service
sonar.projectName=Payment Service
sonar.projectVersion=1.0.0
sonar.description=Microservice handling payments

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,tests/**,coverage/**
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js,tests/**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/node_modules/**,tests/**
