apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: study-smart
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream payment {
            server payment-service:3001;
        }
        
        upstream forum {
            server forum-service:3002;
        }
        
        upstream crud {
            server crud-service:3003;
        }
        
        upstream frontend {
            server frontend-service:80;
        }
        
        server {
            listen 80;
            server_name api.studysmart.com;
            
            location /api/payments/ {
                proxy_pass http://payment/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /api/forum/ {
                proxy_pass http://forum/;
                proxy_set_header Host $host;
            }
            
            location /api/ {
                proxy_pass http://crud/;
                proxy_set_header Host $host;
            }
        }
        
        server {
            listen 80;
            server_name studysmart.com;
            
            location / {
                proxy_pass http://frontend/;
                proxy_set_header Host $host;
            }
        }
    }
