apiVersion: v1
kind: Service
metadata:
  name: crud-service
  namespace: study-smart
spec:
  selector:
    app: crud-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  type: ClusterIP