apiVersion: v1
kind: Service
metadata:
  name: forum-service
  namespace: study-smart
spec:
  selector:
    app: forum-service
  ports:
  - port: 3002
    targetPort: 3002
    name: http
  type: ClusterIP
