apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: study-smart
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: ClusterIP